CREATE TABLE BANKACCOUNTS (
    BALANCE double,
    ACCOUNTOWNER varchar(255),
    ACCOUNTTYPE varchar(255),
    ACCOUNTID int,
    UNIQUE (ACCOUNTID)
);

SELECT * FROM TABISH.BANKACCOUNTS FETCH FIRST 100 ROWS ONLY;